# Generated by Django 4.2.2 on 2023-06-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_formdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='em',
            field=models.EmailField(max_length=20),
        ),
    ]
