# Generated by Django 4.2.2 on 2023-06-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_formdata_em'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formdata',
        ),
    ]
